package com.hitsz.front;

import com.Hitsz.common.utils.JwtUtil;
import com.github.xiaoymin.swaggerbootstrapui.annotations.EnableSwaggerBootstrapUI;
import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.context.annotation.Bean;
import springfox.documentation.swagger2.annotations.EnableSwagger2;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@EnableSwaggerBootstrapUI
@EnableSwagger2
//启动dubbo服务
@EnableDubbo
@SpringBootApplication(exclude = DataSourceAutoConfiguration.class)
public class MircWebApplication {

    @Value("${jwt.secret}")
    private String secretKey;

    @Bean
    public JwtUtil jwtUtil(){
        return new JwtUtil(secretKey);
    }

    public static void main(String[] args) {
        SpringApplication.run(MircWebApplication.class, args);
    }

}
