package com.hitsz;

import com.hitsz.task.TimmerTask;
import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.context.ApplicationContext;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@EnableDubbo
//启动定时任务
@EnableScheduling
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
public class MircTaskApplication {

	public static void main(String[] args) {
	    ApplicationContext context = SpringApplication.run(MircTaskApplication.class, args);
		TimmerTask taskManger = context.getBean("taskManger",TimmerTask.class);
		//taskManger.invodeGeneratePlan();
		taskManger.invokeIncomeBack();
	}

}
