spring:
  application:
    name: mirc-web
  #解决swagger路径匹配问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #配置redis
  redis:
    port: 6379
    host: localhost
#???
server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#dubbo??
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.hitsz.front
  consumer:
    check: false
    timeout: 50000
    retries: 0
#短信配置
jdwx:
  realname:
    url: https://way.jd.com/youhuoBeijing/test
    appkey: 3680fa919b771148da626bbcbd459475
  sms:
    url: https://way.jd.com/chuangxin/dxjk
    appkey: 3680fa919b771148da626bbcbd459475
    content: 【ChatGPT】你的注册验证码是：%s，3分钟内有效，请勿泄露给他人
    loginText: 【ChatGPT】你的登录验证码是：%s，3分钟内有效，请勿泄露给他人

#密钥用来生成Token
jwt:
  secret: 342903934cb944808920b642616b3e76